# Generated by Django 4.2.6 on 2023-10-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('article', 'Article'), ('video', 'video')], default='article', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('published', 'Published')], default='draft', max_length=25),
        ),
    ]
