# Generated by Django 4.2.6 on 2023-11-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_lesson_lesson_type_lesson_status_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lesson_type',
            field=models.CharField(choices=[('article', 'Article'), ('video', 'video')], default='article', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
